Repository plants-studio/plants-ui, pull requests merged in 2020-11, with the labels that each got.

#2 Release : 빌드된 후 SVG가 resizing되지 않는 문제 해결
  .DS_Store
  .babelrc
  .gitignore
  .storybook/webpack.config.js
  dist/index.js
  dist/types/Icon/Icon.d.ts
  dist/types/Icon/svg/index.d.ts
  dist/types/button/basic-button/Button.d.ts
  dist/types/button/nav-button/NavButton.d.ts
  dist/types/index.d.ts
  dist/types/text/content-type/ContentType.d.ts
  dist/types/text/header/Header.d.ts
  dist/types/text/sub-header/SubHeader.d.ts
  package.json
  rollup.config.js
  src/.DS_Store
  src/Icon/.DS_Store
  src/Icon/Icon.stories.tsx
  src/Icon/Icon.tsx
  src/Icon/svg/.DS_Store
  src/Icon/svg/community.svg
  src/Icon/svg/gameController.svg
  src/Icon/svg/index.ts
  src/Icon/svg/trophy.svg
  src/Icon/svg/vial-solid.svg
  src/button/basic-button/Button.stories.tsx
  src/button/basic-button/Button.tsx
  src/button/nav-button/NavButton.stories.tsx
  src/button/nav-button/NavButton.tsx
  src/index.ts
  src/text/content-type/ContentType.stories.tsx
  src/text/content-type/ContentType.tsx
  src/text/header/Header.stories.tsx
  src/text/header/Header.tsx
  src/text/sub-header/SubHeader.stories.tsx
  src/text/sub-header/SubHeader.tsx
  src/typing.d.ts
  tsconfig.json
  yarn-error.log
  yarn.lock
Labels: bug

#7 Card 컴포넌트 추가
  src/card/Card.stories.tsx
  src/card/Card.tsx
  src/card/lolimage.jpg
  src/typing.d.ts
Labels: enhancement

#9 Sticker 컴포넌트 추가
  src/sticker/Sticker.stories.tsx
  src/sticker/Sticker.tsx
Labels: enhancement

#12 Header, SubHeader, ContentType 컴포넌트 추가
  src/text/content-type/ContentType.stories.tsx
  src/text/content-type/ContentType.tsx
  src/text/header/Header.stories.tsx
  src/text/header/Header.tsx
  src/text/sub-header/SubHeader.stories.tsx
  src/text/sub-header/SubHeader.tsx
  yarn.lock
Labels: enhancement

#13 IconButton 컴포넌트, Type.ts 추가, Button, Icon 컴포넌트 리팩토링
  src/Icon/Icon.tsx
  src/button/basic-button/Button.stories.tsx
  src/button/basic-button/Button.tsx
  src/button/icon-button/IconButton.stories.tsx
  src/button/icon-button/IconButton.tsx
  src/util/Type.ts
Labels: enhancement

#15 Release/1.0.4
  dist/index.js
  dist/types/Icon/Icon.d.ts
  dist/types/Icon/svg/index.d.ts
  dist/types/button/basic-button/Button.d.ts
  dist/types/text/content-type/ContentType.d.ts
  dist/types/text/header/Header.d.ts
  dist/types/text/sub-header/SubHeader.d.ts
  package.json
  src/Icon/svg/discordSolid.svg
  src/Icon/svg/home.svg
  src/Icon/svg/index.ts
Labels: Release

#16 Fix : handling onClick, isSelected props
  src/button/nav-button/NavButton.stories.tsx
  src/button/nav-button/NavButton.tsx
Labels: bug

#17 Hotfix/export type
  dist/index.js
  dist/types/button/nav-button/NavButton.d.ts
  dist/types/index.d.ts
  package.json
  src/index.ts
Labels: bug

#20 Card.tsx 에 overflow hidden 추가
  src/card/Card.tsx
Labels: enhancement

#19 Header, SubHeader css 수정
  src/text/header/Header.tsx
  src/text/sub-header/SubHeader.tsx
Labels: enhancement

#21 IconButton css 수정
  src/button/icon-button/IconButton.tsx
Labels: enhancement

#22 Sticker 컴포넌트 스타일 코드 및 props 추가
  dist/index.js
  package.json
  src/sticker/Sticker.tsx
Labels: enhancement

#23 Progress 컴포넌트 position 버그 수정 및 height props 추가
  dist/index.js
  dist/types/index.d.ts
  package.json
  src/visibility/progress/Progress.stories.tsx
  src/visibility/progress/Progress.tsx
Labels: bug, enhancement

#24 Progress 컴포넌트 opacity bug 수정
  dist/index.js
  package.json
  src/visibility/progress/Progress.stories.tsx
  src/visibility/progress/Progress.tsx
Labels: bug

#25 Header 컴포넌트 css 속성 수정
  dist/index.js
  package.json
  src/text/header/Header.stories.tsx
  src/text/header/Header.tsx
Labels: enhancement

#26 SubHeader 컴포넌트의 css 수정
  src/text/sub-header/SubHeader.stories.tsx
  src/text/sub-header/SubHeader.tsx
Labels: enhancement
